services:
  backend:
    image: notdonny/clouddrive-backend:latest
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATA_DIR=/app/data
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
    restart: unless-stopped

  frontend:
    image: notdonny/clouddrive-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
